### ISSUE TITLE
add data discovery resources

### ISSUE THREAD

**Issue by reblake** [SESYNC-ci/online-data-lesson#2]
Even thought this lesson is written in Python, it would be good to alert learners to the following resources in this lesson: 
1) data discovery through DataONE network    https://search.dataone.org/data
2) CRAN taskview for open data available in R     https://github.com/ropensci/opendata

**Comment by reblake** [comment]
Also metajam R package for downloading data and metadata from DataONE: https://nceas.github.io/metajam/

**Comment by andGarc** [comment]
I have added links and short descriptions to the resources mentioned. 
CRAN taskview for open data has been archived. I did not include it.
